# fly.toml app configuration file generated for pcr-cb-discord-bot on 2023-06-26T19:47:26+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pcr-cb-discord-bot"
primary_region = "sin"
